--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/openjdk:8-jdk"
    environment: 
      JVM_OPTS: "-Xmx3200m"
      TERM: dumb
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"build.gradle\" }}"
            - v1-dependencies-
      - 
        run: "gradle dependencies"
      - 
        run: "gradle build"
      - 
        run: 
          command: |
              curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
              sudo dpkg -i cf-cli_amd64.deb
              cf -v
              cf api https://api.run.pivotal.io  # alternately target your private Cloud Foundry deployment
              cf auth "rrafaelpaz@gmail.com" "!Cranberries@2018"
              
          name: "Setup CF CLI"
      - 
        run: 
          command: cf target -o rafaelpaz -s rafaelTargetSpace
          name: "Setting up Org and target space"
      -
        run: cf create-route rafaelTargetSpace shared-simpleapi --hostname simpleapi
      - 
        run: 
          command: cd /tmp/app/build/libs && cf push simpleapi -p rafaelsimpleapi-0.0.1-SNAPSHOT.jar
          name: "Pushing app"
          
      - 
        run: cf logs simpleapi --recent
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"build.gradle\" }}"
          paths: 
            - ~/.gradle
      - 
        run: "gradle test"
    working_directory: /tmp/app
version: 2
